import Game.Levels.NaturalNumbersWorld.L01_Numerals
import Game.Levels.NaturalNumbersWorld.L02_NormalForms
import Game.Levels.NaturalNumbersWorld.L03_Induction
import Game.Levels.NaturalNumbersWorld.L04_Recursion
import Game.Levels.NaturalNumbersWorld.L05_DefiningAddition
import Game.Levels.NaturalNumbersWorld.L06_AddingZero
import Game.Levels.NaturalNumbersWorld.L07_AddingSuccessors
import Game.Levels.NaturalNumbersWorld.L08_CommutingAddition
import Game.Levels.NaturalNumbersWorld.L09_SuccessorInjectivity

World "NaturalNumbersWorld"
Title "Natural Numbers World"

Introduction "In this world, we will introduce the type `ℕ` of natural numbers.

In traditional foundations, the natural numbers are characterized by a series of axioms discovered roughly contemporaneously by Dedekind and Peano that are commonly called the *Peano postulates*. There are five axioms:

  1. There is a natural number `0 : ℕ` called *zero*.

  2. There is a function `succ : ℕ → ℕ` that sends any natural number to its *successor*.

  3. The successor function is injective: `∀ m n : ℕ, succ m = succ n → m = n`.

  4. Zero is not the successor of any natural number: `¬ (∃ n : ℕ, succ n = 0)`.

  5. The principle of mathematical induction: `∀ P : ℕ → Prop, P 0 → (∀ k : ℕ, P k → P (succ k)) → (∀ n : ℕ, P n)`.

In type theory, the type `ℕ` of natural numbers is instead characterized by introduction and elimination rules:

* The *introduction rules* tell us that there is a natural number `0 : ℕ` as well as natural numbers obtained by applying the function `succ : ℕ → ℕ`.
* The *elimination rule* extends the principle of mathematical induction to families of types as well as families of propositions: `∀ P : ℕ → Type, P 0 → (∀ k : ℕ, P k → P (succ k)) → (∀ n : ℕ, P n)`.

Together these rules say that `ℕ` is an *inductive type* freely generated by `0 : ℕ` and `succ : ℕ → ℕ`. We may define (dependent) functions out of the inductive type `ℕ` &ldquo;by induction&rdquo; by considering only the cases of `0` and `succ n` for some `n : ℕ`.

The type-theoretic definition of `ℕ` closely resembles Peano's first, second, and fifth axioms and in fact implies the other two, as we will see by the end of this world.
"
